CED-721 Add EsCta component
EnergySage/es-ds pull request #1039
Opened 2023-07-11 16:35 UTC by jsieving

### 🔗 Linked issue

https://energysage.atlassian.net/browse/CED-721

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

- Created new `EsCta` component which can be customized for the different use cases described in the ticket.
  - Right now, the component only works on the demo page. It's also copied over to a component Vue file, but there are some errors in building it.
- Updated the documentation with all the attributes of the component
  - Once I can get the component file working, I will update with more examples that reflect each use case shown in the ticket.

Feedback requested/issues:

- @RyanMulready these seem like environment/package issues:
  - Importing from `@energysage/es-vue-base` in `EsCta.vue` doesn't work (it says the module path can't be resolved.) Importing from `../..` gets rid of warnings in VSCode, but also fails to build.
  - Container queries don't seem to work in `EsCta.vue` even though they work in `es-cta.vue`. I also see scss warnings in the code that the `container-*` properties are unknown.
- For the link - @tomleo you usually have good ideas about forms:
  - When `showForm` is `false`, I use the whole card as a link. Is that bad, because it's putting block components in an inline component? Should I use `@click` instead and change the `window.location.href`?
  - When `showForm` is `true` but `showZipEntry` is `false`, clicking the button takes you to the destination URL with a "?" appended. Is this bad, and should I find some way to prevent that when the form submits?

### 🥼 Testing

- Go to http://localhost:8500/molecules/es-cta

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.
- [x] I have documented testing approach

2023-07-12 18:27 UTC, tomleo reviewed
I took a quick pass at things, overall look good. I'll take a deeper dive into things a little later.

2023-07-12 21:57 UTC, RyanMulready reviewed
> @RyanMulready these seem like environment/package issues:
    Importing from @energysage/es-vue-base in EsCta.vue doesn't work (it says the module path can't be resolved.) 

When inside `es-vue-base` self imports should be treated like any other project:
```javascript
import {
    formMixins,
} from '../lib-mixins';
import {
    vuelidateMinLength,
    vuelidateMaxLength,
    vuelidateNumeric,
    vuelidateRequired,
} from '../lib-validators';
```

> Container queries don't seem to work in EsCta.vue even though they work in es-cta.vue. I also see scss warnings in the code that the container-* properties are unknown.

I don't see any errors/warnings. Can you show me what they say and/or maybe point at a specific container style that isn't working as expected?

2023-07-13 19:39 UTC, jsieving commented
@RyanMulready, thanks, I had a brain blip with the imports. 
This is what I mean about warnings (I see the same thing in `EsCta.vue` and `es-cta.vue`):
<img width="460" alt="Screenshot 2023-07-13 at 3 01 13 PM" src="https://github.com/EnergySage/es-ds/assets/31548155/737803c2-6fc6-43c9-9674-8f7a3822af85">
It might just be my editor config being screwed up, but I thought I should point it out since the container queries weren't working on `EsCta.vue`.

Here's what I'm talking about (click to expand). The PR has been updated to demo this as well.
<img width="150" alt="Screenshot 2023-07-13 at 3 36 34 PM" src="https://github.com/EnergySage/es-ds/assets/31548155/59396c97-9525-49c5-8d11-4ab1d63f1fb6"><img width="150" alt="Screenshot 2023-07-13 at 3 36 51 PM" src="https://github.com/EnergySage/es-ds/assets/31548155/d290ee18-74b4-4a2e-a7d5-7d5ca41d1b70"><img width="150" alt="Screenshot 2023-07-13 at 3 37 03 PM" src="https://github.com/EnergySage/es-ds/assets/31548155/1bac1dfa-4c39-478d-8f8a-080aa70d9f8d">

2023-07-13 19:48 UTC, jsieving commented on es-design-system/pages/molecules/es-cta.vue
> +    flex-direction: column;
Utility classes get `!important`, and I thought having to use the stylesheet for both cases was better than adding another `!important`.

2023-07-13 20:16 UTC, jsieving commented on es-design-system/pages/molecules/es-cta.vue
> +            return !this.url.includes('www.energysage.com');
You're right that hard coding it isn't great. Having that as a required prop seemed a little inconvenient, and I think I can accomplish the same thing with `window.location.host`. Let me know if you see any issues with what I did.

2023-07-13 20:16 UTC, jsieving commented on es-vue-base/src/lib-components/EsCta.vue
> +            return !this.url.includes('www.energysage.com');
Same as above - using `window.location.host`

2023-07-13 20:18 UTC, jsieving commented on es-vue-base/src/lib-components/EsCta.vue
> +        privacyPolicyLink: {
It was specified in the ticket to use that as the default, so I'm not sure. @RyanMulready, since I believe you wrote that up, what do you think?

2023-07-14 19:12 UTC, RyanMulready commented
> @RyanMulready, thanks, I had a brain blip with the imports. This is what I mean about warnings (I see the same thing in `EsCta.vue` and `es-cta.vue`): <img alt="Screenshot 2023-07-13 at 3 01 13 PM" width="460" src="https://user-images.githubusercontent.com/31548155/253381808-737803c2-6fc6-43c9-9674-8f7a3822af85.png"> It might just be my editor config being screwed up, but I thought I should point it out since the container queries weren't working on `EsCta.vue`.
> 
> Here's what I'm talking about (click to expand). The PR has been updated to demo this as well. <img alt="Screenshot 2023-07-13 at 3 36 34 PM" width="150" src="https://user-images.githubusercontent.com/31548155/253389384-59396c97-9525-49c5-8d11-4ab1d63f1fb6.png"><img alt="Screenshot 2023-07-13 at 3 36 51 PM" width="150" src="https://user-images.githubusercontent.com/31548155/253389401-d290ee18-74b4-4a2e-a7d5-7d5ca41d1b70.png"><img alt="Screenshot 2023-07-13 at 3 37 03 PM" width="150" src="https://user-images.githubusercontent.com/31548155/253389408-1bac1dfa-4c39-478d-8f8a-080aa70d9f8d.png">

I do not see those warnings myself. I haven't used containers myself, they are relatively new. However I think you might be using `container-name` wrong? Looking at the [docs](https://developer.mozilla.org/en-US/docs/Web/CSS/container-name#using_a_container_name) I think something like this might be what you're after

```css
@container card (min-width: 600px) {
    .flex-layout-outer {
        display: flex;
    }
}
```

2023-07-17 16:54 UTC, ericdouglaspratt requested changes
I'd like to make a few suggestions that will hopefully simplify things and make this easier to reason about:
- EsCta should probably be an organism rather than a molecule, because it's made up of a bunch of molecules.
- I recognize Ryan specified the props a certain way in the ticket, however I feel pretty strongly that we should pull the zip code form functionality out into its own organism component, EsZipCodeForm. We can still do that as part of this ticket and PR.
    - EsCta can then take a `<slot name="cta" />` and on the docs page, we can show a few examples of what you could pass in there - either nothing (for case of the cross-sell card), or a button, or EsZipCodeForm.
    - This would greatly reduce the number of props coming into this component, which would reduce the risk of unexpected interactions between them, as well as make the zip code form logic easier to reason about.
- I think we should also separate the full-width banners from the card-like ones that will always live within a constrained column width on a page.
    - I think it'll be too difficult to ensure the layout works if we mix these two use cases into one component. The full-width banners never have an image or supporting text, so making the side-by-side layout work in cases where people happen to add those in is a waste of time. The cards never change layout - their contents are always vertically stacked, and their parent layouts will set them up in a column grid layout so they never grow too wide.
    - The card one could be called something like EsCtaCard, and the full-page-width one could be called EsCtaBanner.

2023-07-17 17:03 UTC, ericdouglaspratt commented on es-vue-base/src/lib-components/EsCta.vue
> +        privacyPolicyLink: {
We probably can't make it required if it's possible to turn the form off entirely, but see my comment below about extracting the zip code form out to its own component.

In that component, however, we should be able to remove the default and make it required. Privacy policy could shift URLs in the future, or we could end up using this on other subdomains (possibly), so we should make it as domain-agnostic as possible and take all URLs as input.

2023-07-21 13:04 UTC, tomleo commented
> When showForm is false, I use the whole card as a link. Is that bad, because it's putting block components in an inline component? Should I use @click instead and change the window.location.href? -- @jsieving 

In [HTML5](https://w3c.github.io/html-reference/a.html#a-changes) pretty much everything can be nested inside an anchor-tag (including block-level elements), with the exception of `<button>` and other `<a>` tags.

2023-07-21 15:45 UTC, tomleo approved these changes
Overall looks good 👍

2023-07-21 15:45 UTC, tomleo commented on es-design-system/pages/organisms/es-cta-card.vue
> +                <template #cta>
For this example I'd recommend either making the button a link (there's an attribute you can pass to `es-button` that will do that), or make this a form i.e.

```html
<form
    method="GET"
    action="https://design.energysage.dev/">
    <es-button type="submit">
        Get quotes
    </es-button>
</form>
```

2023-07-26 12:44 UTC, ericdouglaspratt approved these changes
Simplified the components a bit, removed props I don't think we need to match the designs, converted several text props to slots, added more robust docs and examples.

2023-07-26 12:44 UTC, merged