CED-800: update EsAccordion to use heading tags
EnergySage/es-ds pull request #1089
Opened 2023-08-02 17:41 UTC by suleiy

### 🔗 Linked issue

- https://energysage.atlassian.net/browse/CED-800

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

- Update EsAccordion to use heading tags
    - Accepts a headingTag parameter that defaults to 'h3'
    - Includes a <button> tag,  positioned over on top of the 'h3' tag  and contains hidden text to show 'collapse' or 'expand'

### 🥼 Testing

- Updated the EsAccordionList.spec.js test file

#### 🧐 Feedback Requested / Focus Areas

- I'm unsure about how the button should include hidden text. Currently, I have the 'collapse/expand' texts in a span and hidden display.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.
- [x] I have documented testing approach

2023-08-09 18:30 UTC, ericdouglaspratt requested changes
Nice work! A couple things.

2023-08-09 18:30 UTC, ericdouglaspratt commented on es-vue-base/src/lib-components/EsAccordion.vue
> +                <span class="d-none">{{ isVisible ? 'collapse' : 'expand' }}</span>
If we replace the `d-none` here with the `sr-only` class, this text will be readable by screen readers, but still visually hidden, via some `position: absolute` magic. Screen readers don't read out elements that are `display: none`.

2023-08-09 18:30 UTC, ericdouglaspratt commented on es-vue-base/src/lib-components/EsAccordion.vue
> +                class="EsAccordion-heading mb-0 h-auto align-items-center d-flex font-weight-bold justify-content-between px-100 px-sm-200 py-100 rounded-0 text-body text-left text-decoration-none"
A couple things here:
- Some of these utility classes were only here to override certain EsButton styles (at least `h-auto`, `font-weight-bold`, `rounded-0`, `text-left`, `text-decoration-none`, I believe), and we may no longer need them. Can we remove the unnecessary ones?
- Changing the default to an `<h3>` is appropriate, but it does dramatically change the rendered text size on desktop. [CED-799](https://energysage.atlassian.net/browse/CED-799) will solve for the ability to pass in a `variant` prop to customize the font size, among other styling, but in order to minimize breaking visual changes in this PR (and set up what will be needed for the `'default'` variant, let's set `font-size-100` here to keep it the same size it was before.

2023-08-09 18:30 UTC, ericdouglaspratt commented on es-vue-base/src/lib-components/EsAccordion.vue
> +            class="position-relative d-inline-block w-100">
Would removing the `d-inline-block w-100` still work, as I believe the `<header>` tag would render at its default `display: block` and go the full width? If so, could be simpler.

2023-08-09 18:30 UTC, ericdouglaspratt commented on es-design-system/pages/molecules/es-accordion.vue
> +                        For example, if the accordion is used within a section that is already under an <h3>, it may need to be an h4.
I'm seeing a line length warning on this line, probably just need to line break mid-way through.

2023-08-10 14:49 UTC, suleiy commented
Made changes to add transition to the header and also add/remove classes, thanks!

2023-08-14 15:37 UTC, ericdouglaspratt requested changes
Looks awesome - just one item on reduced motion and this should be good to go.

2023-08-16 13:33 UTC, ericdouglaspratt approved these changes
Nice work!

2023-08-16 20:52 UTC, merged