feat: add arrows prop
EnergySage/es-ds pull request #1169
Opened 2023-08-22 19:46 UTC by suleiy

### 🔗 Linked issue

https://energysage.atlassian.net/browse/CED-667
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

In ArticleRelated desktop design, it has arrows to navigate through the horizontal list. Added a prop to have the option to use arrows in desktop. 

### 🥼 Testing

Manual Testing (es-design-system/pages/molecules/es-horizontal-list.vue)
#### 🧐 Feedback Requested / Focus Areas

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.
- [x] I have documented testing approach

2023-08-23 15:15 UTC, lgeggleston approved these changes
This looks very nice! True to the design and functionality; Tested on multiple viewports and with a non-center aligned version, all look as expected and no change to previous versions.

2023-08-23 17:21 UTC, suleiy commented on es-vue-base/src/lib-components/EsHorizontalList.vue
> +            if (this.activeIndex + indexChange >= 1 && this.activeIndex + indexChange <= this.children.length) {
Fixed, thank you!

2023-08-24 13:41 UTC, ericdouglaspratt requested changes
This is great! It makes EsHorizontalList actually functional for mouse-based users. Two small accessibility changes and then I'd say this is good to go.

2023-08-24 13:41 UTC, ericdouglaspratt commented on es-vue-base/src/lib-components/EsHorizontalList.vue
> +            </es-button>
Can we throw a `<span class="sr-only">Previous</span>` in here for accessibility purposes, so the function if this button is clear to screen readers?

2023-08-24 13:41 UTC, ericdouglaspratt commented on es-vue-base/src/lib-components/EsHorizontalList.vue
> +            </es-button>
Can we throw a `<span class="sr-only">Next</span>` in here for accessibility purposes, so the function if this button is clear to screen readers?

2023-08-24 15:02 UTC, ericdouglaspratt approved these changes
Nice work!

2023-08-24 15:19 UTC, merged