Fix EsFileThumbnail Image Stretching
EnergySage/es-ds pull request #1210
Opened 2023-09-28 17:23 UTC by gigiwargin

### 🔗 Linked issue
https://energysage.atlassian.net/browse/CSM-2856

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [X] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Updated `EsFileThumbnail` to stop stretching images. Most images of standard letter dimensions (8.5" x 11") will appear fine. Extremely wide and short images will also be fine. The outlier is an extremely narrow and tall image, but I expect the use case for this to be small.

### 🥼 Testing

Manual 

#### 🧐 Feedback Requested / Focus Areas

- Do you have concerns about the files that will show a thumbnail with a column of white space (narrow and tall images)?

### 📝 Checklist

- [X] I have linked an issue or discussion.
- [X] I have updated the documentation accordingly.
- [X] I have documented testing approach

2023-10-10 14:51 UTC, satwikgoyal requested changes
@gigiwargin these changes look great! 🪄 I tried some CSS which seem to cover the edge case(s) too, please let me know what are your thoughts on it. Currently it is using the center of the image but we can add the `float` and `vertical-align` css properties if we want to show the top-left corner as the thumbnail cover.

2023-10-10 14:51 UTC, satwikgoyal commented on es-vue-base/src/lib-components/EsFileThumbnail.vue
> +                            <div class="h-100">
```suggestion
                            <div class="image-preview-div">
```

2023-10-10 14:51 UTC, satwikgoyal commented on es-vue-base/src/lib-components/EsFileThumbnail.vue
> +    height: 200%;
```suggestion
    height: 100%;
    object-fit: cover;
    width: 100%;
```

2023-10-10 14:51 UTC, satwikgoyal commented on es-vue-base/src/lib-components/EsFileThumbnail.vue
```suggestion
.image-preview-div {
    height: 100%;
    overflow: hidden;
    width: 100%;
}
```

2023-10-10 20:23 UTC, gigiwargin commented
Ty for the suggestions!!

2023-10-11 13:40 UTC, satwikgoyal approved these changes
Looks great @gigiwargin. Since you were able to use inline styles we can remove the `image-preview-div` class and then we are all set to go.

2023-10-11 13:40 UTC, satwikgoyal commented on es-vue-base/src/lib-components/EsFileThumbnail.vue
> +                            <div class="image-preview-div h-100 w-100 overflow-hidden">
```suggestion
                            <div class="h-100 w-100 overflow-hidden">
```

2023-10-17 18:41 UTC, merged