CED-969-update-LFC-urls-es-nav-bar
EnergySage/es-ds pull request #1230
Opened 2023-10-16 17:51 UTC by suleiy

### 🔗 Linked issue

https://energysage.atlassian.net/browse/CED-969

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

- Update LFC links in EsNavBar to new URLs according to[ site migration sheet](https://docs.google.com/spreadsheets/d/1-A4om_fArblc8s5sLA7XbufWchbh4mtF2om_biABEgc/edit#gid=212067427)
- changed the news urls to www.energysage.com/blog but the content of the link might not be ready

### 🥼 Testing

- manual testing

#### 🧐 Feedback Requested / Focus Areas

- Overall

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.
- [x] I have documented testing approach

2023-10-16 20:01 UTC, ericdouglaspratt requested changes
Nice start! A few comments.

2023-10-16 20:01 UTC, ericdouglaspratt commented on es-vue-base/src/lib-utils/nav-bar-global-content.js
>                      newTab: true,
Anything that was pointing to `NEWS_DOMAIN` before and has `newTab` set to `true` should remove the `newTab: true` line, effectively setting it to `false`, now that everything is on the same domain (and, importantly, has the same navigation).

2023-10-17 13:47 UTC, suleiy commented
Hi @ericdouglaspratt, thanks for the review! I've made the changes

2023-10-17 14:01 UTC, ericdouglaspratt requested changes
Looks good! Just one small thing.

2023-10-17 14:45 UTC, suleiy commented on es-vue-base/src/lib-utils/nav-bar-global-content.js
> +    NEWS_DOMAIN = process.env.NEWS_DOMAIN || 'https://energysage.com',
fixed, thank you!

2023-10-17 17:45 UTC, ericdouglaspratt approved these changes
Nice!

2023-10-17 19:28 UTC, merged