fix: sass warnings
EnergySage/es-ds pull request #1478
Opened 2024-08-14 19:22 UTC by tomleo

### 🔗 Linked issue

- https://energysage.atlassian.net/browse/CED-1731

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

- Upgrade dart-sass version
- Fix deprecation errors (`@debug` was super helpful)

### 🥼 Testing

- `npm run css-compile` in the `es-bs-base` folder/project

#### 🧐 Feedback Requested / Focus Areas

-

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.
- [ ] I have documented testing approach

2024-08-14 19:23 UTC, tomleo commented
This removes the need for https://github.com/EnergySage/es-ds/pull/1471

2024-08-26 21:20 UTC, nathanielwarner requested changes
Following up from the Slack discussion we had, it seems like this is mostly good except for the navbar SASS changes.

2024-08-26 21:20 UTC, nathanielwarner commented on es-bs-base/scss/_navbar.scss
It seems like this file was changed in a way that also makes the styling no longer equivalent, based on building the package and using within the old design system:

![Screenshot 2024-08-14 at 16 12 26 (1)](https://github.com/user-attachments/assets/74664a24-f9e4-479a-92ab-554545b43a88)

2024-08-27 01:56 UTC, tomleo commented
Closing in favor of https://github.com/EnergySage/es-ds/pull/1495

2024-08-27 01:56 UTC, closed without merging