feat: finish EsRating TODOs
EnergySage/es-ds pull request #1517
Opened 2024-09-09 17:40 UTC by hroth1994

### 🔗 Linked issue

https://energysage.atlassian.net/browse/CED-1822

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR adds onto work done in a [previous PR](https://github.com/EnergySage/es-ds/pull/1490) to add EsRating v3 molecule. Remaining items included:
- Create half star functionality for read only ratings
  - Done by not using PrimeVue's rating component for read only ratings
- Fix accessibility label for half stars defaulting to 1
  - Done by adding aria attributes for [slider role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/slider_role)
- tabs "Moves focus to the star representing the value, if there is none then first star receives the focus."
  - Done applying focus style to `data-p-focused='true'` property

### 🥼 Testing

Tested locally on http://localhost:8500/molecules/rating

#### 🧐 Feedback Requested / Focus Areas

- General

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.
- [x] I have documented testing approach

2024-09-11 13:18 UTC, mpleroux commented
👀

2024-09-11 16:07 UTC, nathanielwarner requested changes

2024-09-12 18:02 UTC, hroth1994 commented on es-ds-components/components/es-rating.vue
This is consistent with the [existing functionality](https://design.energysage.dev/molecules/es-rating/), what do we want the expected behavior to be?

2024-09-12 18:17 UTC, nathanielwarner commented on es-ds-components/components/es-rating.vue
Ah yeah that's true, and you can change it with the arrow keys. Though on this new one it seems like the event fires twice when you navigate by keyboard (since the popup appears twice)

2024-09-12 19:25 UTC, hroth1994 commented on es-ds-components/components/es-rating.vue
> +                data-testid="rating-test">
It looks like it's being used in some [tests](https://github.com/search?q=org%3AEnergySage%20rating-test&type=code)?

2024-09-12 19:36 UTC, nathanielwarner commented on es-ds-components/components/es-rating.vue
> +                data-testid="rating-test">
It looks like all but one of those is within the old design system tests themselves, and the other is CDGM.. in any case, not a big deal, but not sure there's any reason to maintain it either

2024-09-18 14:25 UTC, hroth1994 commented on es-ds-components/components/es-rating.vue
> +            },
Added a comment, this seems to be due to a PrimeVue issue where the focus state persists on the item after click

2024-09-18 14:27 UTC, hroth1994 commented on es-ds-components/components/es-rating.vue
Added a comment, this seems to be due to a PrimeVue issue with change events

2024-09-18 14:55 UTC, nathanielwarner approved these changes
LGTM! 🚀 Nice work on this

2024-09-18 15:20 UTC, merged