feat: add cookie notice and preference center links to footer
EnergySage/es-ds pull request #1566
Opened 2024-12-23 19:19 UTC by hroth1994

### 🔗 Linked issue

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

### 🥼 Testing

#### 🧐 Feedback Requested / Focus Areas

-

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.
- [ ] I have documented testing approach

2025-01-15 19:03 UTC, nathanielwarner commented
👀

2025-01-15 19:23 UTC, nathanielwarner requested changes
Otherwise looks good! Nice work on the layout change, and I verified that it works in the GTM preview as well

2025-01-15 19:23 UTC, nathanielwarner commented on es-ds-components/components/icon/ccpa-opt-out.vue
> +        aria-labelledby="California Consumer Privacy Act (CCPA) Opt-Out Icon"
Right now this is not read aloud. It should be [aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label). [aria-labelledby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) is used to reference a different component.

2025-01-17 15:23 UTC, ericdouglaspratt commented on es-ds-components/components/es-footer.vue
> +        // TODO: update with GTM tag in prod once we've gone live
What does this mean? What code would change as a result of this?

2025-01-17 15:31 UTC, hroth1994 commented on es-ds-components/components/es-footer.vue
> +        // TODO: update with GTM tag in prod once we've gone live
I'm not sure if this is a code change or something in GTM, @tomleo may know more since I based this off of https://github.com/EnergySage/es-cms-pages/pull/870

2025-01-17 16:18 UTC, tomleo commented on es-ds-components/components/es-footer.vue
> +        // TODO: update with GTM tag in prod once we've gone live
I can add additional context outside of the repo

2025-01-22 15:03 UTC, ericdouglaspratt approved these changes
Looks good!

It stood out to me that the icon wasn't part of the link, and that clicking the icon did not do anything. I found that Microsoft's icon on [microsoft.com](https://microsoft.com/) includes the icon in the link.

However, I did some research and couldn't find any specific requirement that the icon be part of the link, and from an accessibility standpoint, a link that reads out "Your privacy choices" is probably much clearer than a link that reads out "California Consumer Privacy Act (CCPA) Opt-Out Icon Your privacy choices", so I'm okay with this as is.

2025-01-23 16:02 UTC, merged