fix(esrating): fix aria-valuenow bug
EnergySage/es-ds pull request #912
Opened 2023-06-01 00:23 UTC by RyanMulready

### 🔗 Linked issue

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

### 🥼 Testing

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.
- [ ] I have documented testing approach

2023-06-01 14:33 UTC, ericdouglaspratt requested changes
I'm seeing a few styling regressions as a result of this. We probably also want to wait for Mike to get back so he can test out the nav and footer changes on es-site.

On the mobile EsNavBar, if you go into the "EV chargers" menu (or any of the product menus), the divider line isn't going all the way across and some of the items aren't wrapping and are rendering next to each other. I'm also seeing a horizontal scroll bar in the menus where items appear next to each other.
<img width="355" alt="Screen Shot 2023-06-01 at 10 29 05 AM" src="https://github.com/EnergySage/es-ds/assets/1350363/2afb9c99-592a-4beb-aa5e-9933ba87cb8c">
<img width="358" alt="Screen Shot 2023-06-01 at 10 33 09 AM" src="https://github.com/EnergySage/es-ds/assets/1350363/30e20aef-383a-45cf-b19e-677453160e96">

2023-06-01 14:33 UTC, ericdouglaspratt commented on es-vue-base/src/lib-components/EsNavBarTopicMenu.vue
> +                        class="nav-item pl-3">
This should probably be `pl-100` to match the new spacing naming convention.

2023-06-01 15:08 UTC, RyanMulready commented
> I'm seeing a few styling regressions as a result of this. We probably also want to wait for Mike to get back so he can test out the nav and footer changes on es-site.
> 
> On the mobile EsNavBar, if you go into the "EV chargers" menu (or any of the product menus), the divider line isn't going all the way across and some of the items aren't wrapping and are rendering next to each other. I'm also seeing a horizontal scroll bar in the menus where items appear next to each other. <img alt="Screen Shot 2023-06-01 at 10 29 05 AM" width="355" src="https://user-images.githubusercontent.com/1350363/242630241-2afb9c99-592a-4beb-aa5e-9933ba87cb8c.png"> <img alt="Screen Shot 2023-06-01 at 10 33 09 AM" width="358" src="https://user-images.githubusercontent.com/1350363/242631190-30e20aef-383a-45cf-b19e-677453160e96.png">

Right... `es-site` needs the css 🙃 . I fixed the issue where seeing and made the changes "less breaking". I will name Mike as a reviewer as well.

2023-06-06 02:40 UTC, mpleroux approved these changes
I reviewed the changes and they look fine to me. I also ripped the nav and checked it in es-site. I didn't spot any regressions.

You had initially removed this old selector before putting it back. I originally added it to fix some problem and I don't think it's still necessary:

```scss
// Override BS4 defaults for consistency
.nav-es-container {
...
    .menu {
        ....
        ul, li {
            display: block;
            width: 100%;
            border-style: none;
        }
    }
}
```

Your addition of `width: 100%` to `.nav-item` fixed the problem Eric mentioned.

I examined the `ul` and `li` elements inside `.dropdown-list` which is used by the mobile dropdown menus. You can get to it by inspecting "Tips & guides" then looking for the element with the class `dropdown-list`.

- In the `ul`, the width is overridden by `w-auto` in the HTML, the border style doesn't clear anything, and changing `display` from `block` back to `flex` doesn't have any noticeable effect
- In the `li` elements, those three styles are overridden by others with higher specificity

So I think you can get rid of that selector if you like.

I checked the ripped nav with WAVE and it reported one minor accessibility issue that's unrelated to your PR. It's caused by using the same ID for mobile and desktop form elements. Those IDs need to be refactored anyway because they're using the text of the menu items, spaces and all.

```txt
Multiple form labels
A form control has more than one label associated with it.
```

2023-06-09 21:27 UTC, merged